### ISSUE TITLE
Source code for OpenBSD network stack post?

### ISSUE THREAD

**Issue by lf-** [bijanebrahimi/blog#1]
I found a few typos in the [newest post](http://bijanebrahimi.github.io/blog/openbsds-network-stack-part-1.html) and I would like to fix them in a pull request, but it appears that the source files have not yet been published. Can you please put them up?

Thanks

**Comment by bijanebrahimi** [comment]
Sure, I just [pushed][1] the source files. Hope it helps and thank you for participation :-)

[1]: https://github.com/bijanebrahimi/blog/commit/c9c2682bdde82e9fbd23773593146101a57c71af
